language: go
go_import_path: github.com/csi-driver/csi-driver-smb
dist: bionic

go:
  - "1.13.9"

before_install:
  - GO111MODULE=off go get github.com/mattn/goveralls

script:
  - make verify
  - make container
  - make smb-windows
