language: go
go_import_path: github.com/kubernetes-sigs/azurefile-csi-driver
dist: bionic

env:
  global:
    - GO111MODULE=on

go:
  - "1.12.1"

cache:
  directories:
    - $GOPATH/pkg
    - $GOPATH/bin
    - $GOROOT

jobs:
  include:
    - stage: test
      name: "Code verification"
      script:
        - make verify
    - stage: test
      name: "Unit test"
      install:
        - GO111MODULE=off go get github.com/mattn/goveralls
      script:
        - go test -covermode=count -coverprofile=profile.cov ./pkg/...
    - stage: test
      name: "Sanity test"
      script:
        - make sanity-test
      # after_failure: TRAVIS_TEST_RESULT=0
    - stage: test
      name: "Integration test"
      script:
        - make integration-test
