language: go
go_import_path: github.com/kubernetes-sigs/azurefile-csi-driver
dist: bionic

env:
  global:
    - GO111MODULE=on

go:
  - "1.12.1"

jobs:
  include:
    - stage: build
      name: "Build"
      script:
        - make azurefile-container
        - make azurefile-windows
    - stage: test
      name: "Code verification"
      script:
        - make verify
    - stage: test
      name: "Unit test"
      install:
        - GO111MODULE=off go get github.com/mattn/goveralls
      script:
        - go test -covermode=count -coverprofile=profile.cov ./pkg/...
    - stage: test
      name: "Sanity test"
      install:
        - sudo apt update && sudo apt install cifs-utils procps -y
      script:
        - make sanity-test
      # after_failure: TRAVIS_TEST_RESULT=0
    - stage: test
      name: "Integration test"
      install:
        - GO111MODULE=off go get github.com/rexray/gocsi/csc
        - sudo apt update && sudo apt install cifs-utils procps -y
      script:
        - make integration-test
