apiVersion: v1
entries:
  csi-driver-smb:
  - apiVersion: v1
    appVersion: v1.15.0
    created: "2024-07-18T06:59:59.116464753Z"
    description: SMB CSI Driver for Kubernetes
    digest: fcadda7e1af1bcfbfd42da9f4a02f6baaa96b0b48bafe7241dc4c5a588d9e4b4
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/latest/csi-driver-smb-v1.15.0.tgz
    version: v1.15.0
  - apiVersion: v1
    appVersion: v1.15.0
    created: "2024-07-18T06:59:59.126665562Z"
    description: SMB CSI Driver for Kubernetes
    digest: fcadda7e1af1bcfbfd42da9f4a02f6baaa96b0b48bafe7241dc4c5a588d9e4b4
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v1.15.0/csi-driver-smb-v1.15.0.tgz
    version: v1.15.0
  - apiVersion: v1
    appVersion: v1.14.0
    created: "2024-07-18T06:59:59.12600989Z"
    description: SMB CSI Driver for Kubernetes
    digest: 5d63c8c4824b43ad35f498854be6d24a06e3d7c19a50c57dc5c6de26d7f39850
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v1.14.0/csi-driver-smb-v1.14.0.tgz
    version: v1.14.0
  - apiVersion: v1
    appVersion: v1.13.0
    created: "2024-07-18T06:59:59.124750877Z"
    description: SMB CSI Driver for Kubernetes
    digest: 962ae1f26a13852e86256464e534228ae6118109aeb1e63abbee07ca18809cff
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v1.13.0/csi-driver-smb-v1.13.0.tgz
    version: v1.13.0
  - apiVersion: v1
    appVersion: v1.12.0
    created: "2024-07-18T06:59:59.12353098Z"
    description: SMB CSI Driver for Kubernetes
    digest: eb1f894fa5ad0c20da3b26a3ad4c20857914c8d76a098fd2185ff068d6118ddd
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v1.12.0/csi-driver-smb-v1.12.0.tgz
    version: v1.12.0
  - apiVersion: v1
    appVersion: v1.11.0
    created: "2024-07-18T06:59:59.122589727Z"
    description: SMB CSI Driver for Kubernetes
    digest: ab3cab9509579264ed95e49a0ad077019a52a45b4e6cc436de5b1f70c03699ed
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v1.11.0/csi-driver-smb-v1.11.0.tgz
    version: v1.11.0
  - apiVersion: v1
    appVersion: v1.10.0
    created: "2024-07-18T06:59:59.121823174Z"
    description: SMB CSI Driver for Kubernetes
    digest: 82e460e6fa80da9ca523a86c28e001e15595d27c3507864f2123dbadc64c7fec
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v1.10.0/csi-driver-smb-v1.10.0.tgz
    version: v1.10.0
  - apiVersion: v1
    appVersion: v1.9.0
    created: "2024-07-18T06:59:59.135360154Z"
    description: SMB CSI Driver for Kubernetes
    digest: 5c78c650b9755e508afecb3f6a554c549509023f7b0610b53853a41783d1c08f
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v1.9.0/csi-driver-smb-v1.9.0.tgz
    version: v1.9.0
  - apiVersion: v1
    appVersion: v1.8.0
    created: "2024-07-18T06:59:59.133499239Z"
    description: SMB CSI Driver for Kubernetes
    digest: d19d156c2143d753085bcbcb32506f8ebd7ebdee275e726f9c8d774a1f0b9f34
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v1.8.0/csi-driver-smb-v1.8.0.tgz
    version: v1.8.0
  - apiVersion: v1
    appVersion: v1.7.0
    created: "2024-07-18T06:59:59.132497919Z"
    description: SMB CSI Driver for Kubernetes
    digest: 65594a1ff09d912a33ee0674bba1fad1f7c717638a281fb68bcfa2c98c288453
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v1.7.0/csi-driver-smb-v1.7.0.tgz
    version: v1.7.0
  - apiVersion: v1
    appVersion: v1.6.0
    created: "2024-07-18T06:59:59.131558208Z"
    description: SMB CSI Driver for Kubernetes
    digest: 31dd4c8b0b0d4a61565631aa5b433b18b5375aeb24812bf4fa9958d5b7917485
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v1.6.0/csi-driver-smb-v1.6.0.tgz
    version: v1.6.0
  - apiVersion: v1
    appVersion: v1.5.0
    created: "2024-07-18T06:59:59.130742188Z"
    description: SMB CSI Driver for Kubernetes
    digest: b7dc9e9dc5d46df12a6d1a5643efe86439bff6c36867968f772e6899692083d6
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v1.5.0/csi-driver-smb-v1.5.0.tgz
    version: v1.5.0
  - apiVersion: v1
    appVersion: v1.4.0
    created: "2024-07-18T06:59:59.130135834Z"
    description: SMB CSI Driver for Kubernetes
    digest: 9b1a6166ab72c09d0eefb448ecc998639b9f6255afb00bfc0ae0a4fdad76f119
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v1.4.0/csi-driver-smb-v1.4.0.tgz
    version: v1.4.0
  - apiVersion: v1
    appVersion: v1.3.0
    created: "2024-07-18T06:59:59.129292699Z"
    description: SMB CSI Driver for Kubernetes
    digest: d2236d36f1cb24139ddf87ea87229369ed856efc42330e656330f6cfa7635858
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v1.3.0/csi-driver-smb-v1.3.0.tgz
    version: v1.3.0
  - apiVersion: v1
    appVersion: v1.2.0
    created: "2024-07-18T06:59:59.12745517Z"
    description: SMB CSI Driver for Kubernetes
    digest: 9d7099165db24d5412c95b298a59cca9b233ab8800d04efd34bb055812390915
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v1.2.0/csi-driver-smb-v1.2.0.tgz
    version: v1.2.0
  - apiVersion: v1
    appVersion: v1.1.0
    created: "2024-07-18T06:59:59.120935991Z"
    description: SMB CSI Driver for Kubernetes
    digest: 5b39613c9104db06815ee2d42fec8507c3bb2038264513449079a4eb5b6530a8
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v1.1.0/csi-driver-smb-v1.1.0.tgz
    version: v1.1.0
  - apiVersion: v1
    appVersion: v1.0.0
    created: "2024-07-18T06:59:59.120064404Z"
    description: SMB CSI Driver for Kubernetes
    digest: 3e4721dd007cc51750f7221be8f66ec7e287c83a8cdcfeb9a71c30f526b06dc4
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v1.0.0/csi-driver-smb-v1.0.0.tgz
    version: v1.0.0
  - apiVersion: v1
    appVersion: v0.6.0
    created: "2024-07-18T06:59:59.119472272Z"
    description: SMB CSI Driver for Kubernetes
    digest: 6fc9d05bc78ca98fb17071b7f5ad05b4c071f2403114d72feae99fb89ca1fc9f
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v0.6.0/csi-driver-smb-v0.6.0.tgz
    version: v0.6.0
  - apiVersion: v1
    appVersion: v0.5.0
    created: "2024-07-18T06:59:59.118965554Z"
    description: SMB CSI Driver for Kubernetes
    digest: 8264c6630806325613234c2d7951c188d073607e6f0f89d781ec32afed04157b
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v0.5.0/csi-driver-smb-v0.5.0.tgz
    version: v0.5.0
  - apiVersion: v1
    appVersion: v0.4.0
    created: "2024-07-18T06:59:59.118405329Z"
    description: SMB CSI Driver for Kubernetes
    digest: fb6d581ba5d4d1d78ca468f6daa4a24c47bb147b74d005d3c394521b4e534a3e
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v0.4.0/csi-driver-smb-v0.4.0.tgz
    version: v0.4.0
  - apiVersion: v1
    appVersion: v0.3.0
    created: "2024-07-18T06:59:59.117892083Z"
    description: SMB CSI Driver for Kubernetes
    digest: ee9e58db6d4a95491e2012c6607126bbff827b9c439e90e9a9798d2a73b0cb22
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v0.3.0/csi-driver-smb-v0.3.0.tgz
    version: v0.3.0
  - apiVersion: v1
    appVersion: v0.2.0
    created: "2024-07-18T06:59:59.117254087Z"
    description: SMB CSI Driver for Kubernetes
    digest: 8d8667106306d78dea9f63e5a3e8ee7ad2b60f86bd625f5968e37ca6a0cad317
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v0.2.0/csi-driver-smb-v0.2.0.tgz
    version: v0.2.0
  - apiVersion: v1
    appVersion: latest
    created: "2024-07-18T06:59:59.134451894Z"
    description: SMB CSI Driver for Kubernetes
    digest: 37a15bd85f6f9f2df20aed317d9baa3774128552488d02c2897d561e67777963
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v1.9.0/csi-driver-smb-v0.0.0.tgz
    version: v0.0.0
generated: "2024-07-18T06:59:59.115664324Z"
