apiVersion: v1
entries:
  csi-driver-smb:
  - apiVersion: v1
    appVersion: v0.4.0
    created: "2020-10-06T02:45:33.846857672Z"
    description: SMB CSI Driver for Kubernetes
    digest: fb6d581ba5d4d1d78ca468f6daa4a24c47bb147b74d005d3c394521b4e534a3e
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v0.4.0/csi-driver-smb-v0.4.0.tgz
    version: v0.4.0
  - apiVersion: v1
    appVersion: v0.3.0
    created: "2020-10-06T02:45:33.845894964Z"
    description: SMB CSI Driver for Kubernetes
    digest: ee9e58db6d4a95491e2012c6607126bbff827b9c439e90e9a9798d2a73b0cb22
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v0.3.0/csi-driver-smb-v0.3.0.tgz
    version: v0.3.0
  - apiVersion: v1
    appVersion: v0.2.0
    created: "2020-10-06T02:45:33.845424061Z"
    description: SMB CSI Driver for Kubernetes
    digest: bc0aca4acd74b6c521d85d6d75e1dab22c06dcc9a2e0430abc203a2d5006403d
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v0.2.0/csi-driver-smb-v0.2.0.tgz
    version: v0.2.0
  - apiVersion: v1
    appVersion: latest
    created: "2020-10-06T02:45:33.846331468Z"
    description: SMB CSI Driver for Kubernetes
    digest: 726616076e41190988103004a71710847e95deee700f296730f2c264df269d06
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v0.4.0/csi-driver-smb-latest.tgz
    version: latest
  - apiVersion: v1
    appVersion: latest
    created: "2020-10-06T02:45:33.844857657Z"
    description: SMB CSI Driver for Kubernetes
    digest: 726616076e41190988103004a71710847e95deee700f296730f2c264df269d06
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/latest/csi-driver-smb-latest.tgz
    version: latest
generated: "2020-10-06T02:45:33.842420338Z"
