---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.driver.name }}
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    {{- if .Values.feature.enableInlineVolume }}
    - Ephemeral
    {{- end }}
