{{- if .Values.windows.enabled}}
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-smb-node-win
  namespace: {{ .Release.Namespace }}
{{ include "smb.labels" . | indent 2 }}
spec:
  selector:
    matchLabels:
      app: csi-smb-node-win
  template:
    metadata:
{{ include "smb.labels" . | indent 6 }}
        app: csi-smb-node-win
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      priorityClassName: system-node-critical
      {{- include "smb.pullSecrets" . | indent 6 }}
      containers:
        - name: liveness-probe
          volumeMounts:
            - mountPath: C:\csi
              name: plugin-dir
          image: "{{ .Values.windows.image.livenessProbe.repository }}:{{ .Values.windows.image.livenessProbe.tag }}"
          args:
            - --csi-address=$(CSI_ENDPOINT)
            - --probe-timeout=3s
            - --health-port=29643
            - --v=2
          env:
            - name: CSI_ENDPOINT
              value: unix://C:\\csi\\csi.sock
          imagePullPolicy: {{ .Values.windows.image.livenessProbe.pullPolicy }}
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: node-driver-registrar
          image: "{{ .Values.windows.image.nodeDriverRegistrar.repository }}:{{ .Values.windows.image.nodeDriverRegistrar.tag }}"
          args:
            - --v=2
            - --csi-address=$(CSI_ENDPOINT)
            - --kubelet-registration-path={{ .Values.kubelet.windowsPath }}\\plugins\\smb.csi.k8s.io\\csi.sock
          env:
            - name: CSI_ENDPOINT
              value: unix://C:\\csi\\csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: {{ .Values.windows.image.nodeDriverRegistrar.pullPolicy }}
          volumeMounts:
            - name: plugin-dir
              mountPath: C:\csi
            - name: registration-dir
              mountPath: C:\registration
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: smb
          image: "{{ .Values.image.smb.repository }}:{{ .Values.image.smb.tag }}"
          imagePullPolicy: {{ .Values.image.smb.pullPolicy }}
          args:
            - "--v={{ .Values.node.logLevel }}"
            - --endpoint=$(CSI_ENDPOINT)
            - --nodeid=$(KUBE_NODE_NAME)
            - "--metrics-address=0.0.0.0:{{ .Values.node.metricsPort }}"
          ports:
            - containerPort: 29643
              name: healthz
              protocol: TCP
            - containerPort: {{ .Values.node.metricsPort }}
              name: metrics
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
          env:
            - name: CSI_ENDPOINT
              value: unix://C:\\csi\\csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: kubelet-dir
              mountPath: {{ .Values.kubelet.windowsPath }}\
            - name: plugin-dir
              mountPath: C:\csi
            - name: csi-proxy-fs-pipe
              mountPath: \\.\pipe\csi-proxy-filesystem-v1beta1
            - name: csi-proxy-smb-pipe
              mountPath: \\.\pipe\csi-proxy-smb-v1beta1
          resources:
            limits:
              cpu: 400m
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 20Mi
      volumes:
        - name: csi-proxy-fs-pipe
          hostPath:
            path: \\.\pipe\csi-proxy-filesystem-v1beta1
            type: ""
        - name: csi-proxy-smb-pipe
          hostPath:
            path: \\.\pipe\csi-proxy-smb-v1beta1
            type: ""
        - name: registration-dir
          hostPath:
            path: {{ .Values.kubelet.windowsPath }}\plugins_registry\
            type: Directory
        - name: kubelet-dir
          hostPath:
            path: {{ .Values.kubelet.windowsPath }}\
            type: Directory
        - name: plugin-dir
          hostPath:
            path: {{ .Values.kubelet.windowsPath }}\plugins\smb.csi.k8s.io\
            type: DirectoryOrCreate
{{- end -}}
