
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-attacher
  # replace with non-default namespace name
  namespace: {{ .Release.Namespace }}
{{ include "azurefile.labels" . | indent 2 }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-driver-registrar
  # replace with non-default namespace name
  namespace: {{ .Release.Namespace }}
{{ include "azurefile.labels" . | indent 2 }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-provisioner
  # replace with non-default namespace name
  namespace: {{ .Release.Namespace }}
{{ include "azurefile.labels" . | indent 2 }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-snapshotter
{{ include "azurefile.labels" . | indent 2 }}
{{- end -}}
