image:
  azurefile:
    repository: mcr.microsoft.com/k8s/csi/azurefile-csi
    tag: latest
    pullPolicy: Always
  csiProvisioner:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-provisioner
    tag: v1.4.0
    pullPolicy: Always
  csiAttacher:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-attacher
    tag: v1.2.0
    pullPolicy: Always
  clusterDriverRegistrar:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-cluster-driver-registrar
    tag: v1.0.1
    pullPolicy: Always
  csiSnapshotter:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-snapshotter
    tag: v1.1.0
    pullPolicy: Always
  livenessProbe:
    repository: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe
    tag: v1.1.0
    pullPolicy: Always
  nodeDriverRegistrar:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar
    tag: v1.1.0
    pullPolicy: Always

serviceAccount:
  create: true

rbac:
  create: true

controller:
  replicas: 3